### ISSUE TITLE
Derivative Issue 

### ISSUE THREAD

**Issue by RafeyTahir** [BTelsang/Model-free-Control#2]
Dear Telsang,
can you plz explain this part of your code
setpoint = 3*ones(1,length(timevector));
G_inertialComp = tf(1,[1 1]);
ref = lsim(G_inertialComp,setpoint,timevector)';
G_inertialComp_ddt = tf([1 0],[1 1]);
dref = lsim(G_inertialComp_ddt,setpoint,timevector)';

i'm facing the deficulty in understanding the derivative. how you have computed the derivative of Tf (1/1+s) to (s/s+1).

**Comment by BTelsang** [comment]
I computed the derivative using the properties of the Laplace transform (assuming zero initial conditions). You might find this link helpful: https://lpsa.swarthmore.edu/LaplaceXform/FwdLaplace/LaplaceProps.html
Additionally, instead of using "setpoint" variable, it is a general practice to run the setpoint through a filter to smoothen the signal before using it as a reference. The filter in this case is the transfer function 1/(s+1).
